"""Coarse trend categories: substring cues (order = first match wins)."""

TREND_TYPE_RULES: tuple[tuple[str, frozenset[str]], ...] = (
    (
        "technology",
        frozenset(
            {
                "tesla",
                "ai",
                "robot",
                "robotics",
                "tech",
                "iphone",
                "openai",
                "startup",
                "semi",
                "truck",
                "roadster",
                "apple",
                "pixel",
                "surface",
            }
        ),
    ),
    (
        "beauty_lifestyle",
        frozenset(
            {
                "hair",
                "beauty",
                "makeup",
                "skin",
                "routine",
                "fashion",
                "skincare",
                "dress",
                "outfit",
                "clothe",
                "style",
            }
        ),
    ),
    (
        "entertainment",
        frozenset(
            {
                "movie",
                "trailer",
                "comix",
                "comic",
                "film",
                "tv",
                "celebrity",
                "actor",
                "music",
                "song",
                "acoustic",
                "beyonce",
                "swift",
                "marshmello",
                "gomez",
                "selena",
                "paramore",
                "twice",
                "fallon",
                "colbert",
                "corden",
                "snl",
                "letterman",
            }
        ),
    ),
    (
        "seasonal",
        frozenset(
            {
                "winter",
                "summer",
                "holiday",
                "christmas",
                "fall",
                "spring",
                "seasonal",
            }
        ),
    ),
    (
        "food",
        frozenset(
            {
                "recipe",
                "food",
                "steak",
                "pizza",
                "chef",
                "cook",
                "cooking",
                "kitchen",
                "ramsay",
                "ice",
                "cream",
                "cheese",
                "roll",
            }
        ),
    ),
)
